services:

  backend:
    depends_on:
      - database
    build: ./new-ar-menu-api
    ports:
      - 5000:5000
    environment:
      DB_URL: mongodb://database:27017/ar_menu_db

  database:
    image: mongo:7.0.16-jammy
    ports:
      - 27017:27017
    volumes:
      - armenu:/data/db

volumes:
  armenu: